# Generated by Django 4.2 on 2023-10-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20231030_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
